---
title: "População de Salvador:"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    theme: cosmo
    orientation: rows
    vertical_layout: fill
#    vertical_layout: scroll
---



```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(ggplot2)
library("readr")
library("dplyr")
library("tidyr")
library(ggthemes)
library(extrafont)
library(gganimate)
library(ggplotlyExtra)
library(plotly)
library(ggplotify)


#library(echarts4r) # charts
library(tidyverse) # general use
library(lubridate) # dates and times
#library(prophet) # forecasting
library(scales)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(rlang)   # !!sym()


library(plyr)

library(reshape2)

library(tidyr)

# Biblioteca para carregamento automatico de dados 
library(readr)
piramide_v00 <- read_delim("data/piramide_etaria_ssa_2000-2010.csv",";", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"),trim_ws = TRUE)
               
nomes <- levels(as.factor(piramide_v00$ANO_CENSO))
nomes <- as.numeric(nomes)
# Contrucao de graficos

piramide_v00$MASCULINO <- -piramide_v00$MASCULINO

piramide_v00 <- piramide_v00 %>% select(ANO_CENSO,IDADE,MASCULINO,FEMININO) %>% gather(SEXO,POPULACAO,-ANO_CENSO,-IDADE)

populacao_ssa_1549_2000 <- read_delim("data/populacao_ssa_1549-2000.csv",
                                      ";", escape_double = FALSE, trim_ws = TRUE)

```



```{r, echo=FALSE}
selectInput("ano", label = "Ano:",
            choices = nomes, selected = nomes[2])
```
Row 
---------------------------------------------------------------
### Pirâmide Etária Salvador/BA
```{r,eval=TRUE, echo=FALSE}
renderPlotly({
	ggplotly(objeto <- piramide_v00 %>% filter(ANO_CENSO %in% c(input$ano)) %>%
  ggplot(aes(x = IDADE, y = POPULACAO, fill = SEXO)) +
    geom_bar(stat = "identity")+
    scale_fill_manual(breaks = c("MASCULINO","FEMININO"),labels = c("M","F"),values=c("#fac113","#6cbfd3"))+
  #scale_fill_manual(values=c("#fac113","#6cbfd3"))+
  scale_y_continuous(breaks = seq(-15000000, 15000000, 5000000),
                     labels = paste0(as.character(c(seq(15, 0, -5), seq(5, 15, 5))), "m")) +
  coord_flip() +
    theme(axis.title.x = element_text(color = "gray",size = 18)) +
    theme(axis.text.x=element_text(color = "black", size=16, angle=0, vjust=.8, hjust=0.8)) +
    theme(axis.title.y = element_text(color = "gray",size = 18))+
    theme(axis.text.y=element_text(size=16)) +
    theme(axis.text = element_text(size = 16))  +
  #  theme(legend.text = element_text(size = 14)) +
  #  theme(legend.title = element_text(size = 16)) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  theme(legend.title = element_blank())+
    ggtitle(paste(input$ano)) +
    #labs(caption="Fonte: IBGE - SIDRA")+
  labs(caption=paste("Fonte: IBGE - SIDRA",input$ano))+
    theme(legend.position="top")
  #  theme(legend.position = "none")
  )
})
```

### População de Salvador/BA - 1549/2000
```{r,eval=TRUE, echo=FALSE}
ggplotly(objeto<-populacao_ssa_1549_2000 %>% ggplot(aes(x = ANO, y = POPULACAO)) +
  geom_col(stat='identity',position = "dodge")+
  #   geom_col()+
  scale_y_continuous(breaks = seq(0,2500000, 500000),
                     labels = paste0(as.character(c(seq(0.0, 2.5, 0.5))), "M"),
                     limits = c(0,2500000))+  coord_flip() +
  scale_x_continuous(breaks = c(populacao_ssa_1549_2000$ANO[1:5],
                                populacao_ssa_1549_2000$ANO[7],
                                populacao_ssa_1549_2000$ANO[10],
                                populacao_ssa_1549_2000$ANO[13],
                                populacao_ssa_1549_2000$ANO[16]),
                     labels = as.character(c(populacao_ssa_1549_2000$DATA[1:5],
                                             populacao_ssa_1549_2000$DATA[7],
                                             populacao_ssa_1549_2000$DATA[10],
                                             populacao_ssa_1549_2000$DATA[13],
                                             populacao_ssa_1549_2000$DATA[16]))) +
  xlab("ANO") + ylab("Nº") +  labs(fill = "")+
  scale_fill_brewer(palette = "Set1") +
  theme_bw()+
#  theme(axis.title.x = element_text(color = "gray",size = 20)) +
  theme(axis.text.x=element_text(color = "black", size=12, angle=0, vjust=.8, hjust=0.8)) +
  theme(axis.title.y = element_text(color = "gray",size = 20))+
  theme(axis.text.y=element_text(size=12)) +
  theme(axis.text = element_text(size = 12))  +
  theme(legend.text = element_text(size = 14)) +
  theme(legend.title = element_text(size = 16)) +
  #ggtitle("Salvador/BA - 1549/2000") +
  labs(caption="Fonte: IBGE - SIDRA") +
  theme(plot.caption = element_text(hjust = 0.5, face= "italic"), #Default is hjust=1
        #      plot.title.position = "plot", #NEW parameter. Apply for subtitle too.
        plot.caption.position =  "plot") +
  theme(legend.position="bottom"))
```


Column {.tabset .mobile}
-------------------------------------

### Pirâmide Etária Salvador/BA {.mobile}
```{r,eval=TRUE, echo=FALSE}
renderPlotly({
	ggplotly(objeto <- piramide_v00 %>% filter(ANO_CENSO %in% c(input$ano)) %>%
  ggplot(aes(x = IDADE, y = POPULACAO, fill = SEXO)) +
    geom_bar(stat = "identity")+
#    scale_fill_manual(breaks = c("MASCULINO","FEMININO"),labels = c("M","F"),values=c("#fac113","#6cbfd3"))+
  scale_fill_manual(values=c("#fac113","#6cbfd3"))+
  scale_y_continuous(breaks = seq(-15000000, 15000000, 5000000),
                     labels = paste0(as.character(c(seq(15, 0, -5), seq(5, 15, 5))), "m")) +
  coord_flip() +
    theme(axis.title.x = element_text(color = "gray",size = 18)) +
    theme(axis.text.x=element_text(color = "black", size=16, angle=0, vjust=.8, hjust=0.8)) +
    theme(axis.title.y = element_text(color = "gray",size = 18))+
    theme(axis.text.y=element_text(size=16)) +
    theme(axis.text = element_text(size = 16))  +
  #  theme(legend.text = element_text(size = 14)) +
  #  theme(legend.title = element_text(size = 16)) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
#  theme(legend.title = element_blank())+
    ggtitle(paste(input$ano)) +
    #labs(caption="Fonte: IBGE - SIDRA")+
#  labs(caption=paste("Fonte: IBGE - SIDRA",input$ano))+
  #  theme(legend.position="top")
    theme(legend.position = "none")
)
})
```

### População de Salvador/BA - 1549/2000 {.mobile}
```{r,eval=TRUE, echo=FALSE}
ggplotly(objeto<-populacao_ssa_1549_2000 %>% ggplot(aes(x = ANO, y = POPULACAO)) +
  geom_col(stat='identity',position = "dodge")+
  #   geom_col()+
  scale_y_continuous(breaks = seq(0,2500000, 500000),
                     labels = paste0(as.character(c(seq(0.0, 2.5, 0.5))), "M"),
                     limits = c(0,2500000))+  coord_flip() +
  scale_x_continuous(breaks = c(populacao_ssa_1549_2000$ANO[1:5],
                                populacao_ssa_1549_2000$ANO[7],
                                populacao_ssa_1549_2000$ANO[10],
                                populacao_ssa_1549_2000$ANO[13],
                                populacao_ssa_1549_2000$ANO[16]),
                     labels = as.character(c(populacao_ssa_1549_2000$DATA[1:5],
                                             populacao_ssa_1549_2000$DATA[7],
                                             populacao_ssa_1549_2000$DATA[10],
                                             populacao_ssa_1549_2000$DATA[13],
                                             populacao_ssa_1549_2000$DATA[16]))) +
  xlab("ANO") + ylab("Nº") +  labs(fill = "")+
  scale_fill_brewer(palette = "Set1") +
  theme_bw()+
#  theme(axis.title.x = element_text(color = "gray",size = 20)) +
  theme(axis.text.x=element_text(color = "black", size=12, angle=0, vjust=.8, hjust=0.8)) +
  theme(axis.title.y = element_text(color = "gray",size = 20))+
  theme(axis.text.y=element_text(size=12)) +
  theme(axis.text = element_text(size=12))  +
#  theme(legend.text = element_text(size = 14)) +
#  theme(legend.title = element_text(size = 16)) +
  #ggtitle("Salvador/BA - 1549/2000") +
  labs(caption="Fonte: IBGE - SIDRA") +
  theme(plot.caption = element_text(hjust = 0.5, face= "italic"), 
        plot.caption.position =  "plot") +
  theme(legend.position = "none")
)
```


